<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/pinia/authStore'
const router = useRouter(); const auth = useAuthStore(); const orders = ref<any[]>([]); const loading = ref(true); const error = ref('')
onMounted(async () => { if (!auth.isLoggedIn) { router.push('/login'); return } try { const base = import.meta.env.VITE_API_URL || 'http://localhost:4000/api'; const response = await fetch(`${base}/orders`, { headers: { Authorization: `Bearer ${auth.token}` } }); if (!response.ok) throw new Error('Unable to load orders'); orders.value = await response.json() } catch (err) { error.value = err instanceof Error ? err.message : 'Unable to load orders' } finally { loading.value = false } })
</script>
<template><main class="orders-page"><p class="kicker">ACCOUNT</p><h1>Your orders</h1><p v-if="loading">Loading orders...</p><p v-else-if="error" class="error">{{ error }}</p><p v-else-if="!orders.length">You have not placed an order yet.</p><section v-else class="orders-list"><article v-for="order in orders" :key="order._id" class="order-card"><div class="order-heading"><strong>Order #{{ order._id.slice(-6) }}</strong><span>{{ new Date(order.createdAt).toLocaleDateString() }}</span></div><div class="order-items"><div v-for="item in order.items" :key="item.product?._id || item.product" class="order-item"><img :src="item.product?.image || 'https://placehold.co/80x80?text=Product'" :alt="item.product?.title || 'Product'"><span>{{ item.product?.title || 'Product' }} × {{ item.quantity }}</span></div></div><div class="order-total"><span>{{ order.status }}</span><strong>Rs. {{ order.total }}</strong></div><small>{{ order.items.length }} item{{ order.items.length === 1 ? '' : 's' }} · Delivery Rs. {{ order.deliveryFee || 50 }}</small></article></section></main></template>
<style scoped>.orders-page{max-width:850px;margin:auto;padding:48px 24px;color:#15233d}.kicker{color:#2674b8;font-size:.7rem;font-weight:800;letter-spacing:.16em}.orders-page h1{font:500 3rem Georgia,serif;margin:0 0 30px}.orders-list{display:grid;gap:12px}.order-card{border:1px solid #d5e2f0;padding:20px;background:#fff}.order-heading,.order-total{display:flex;justify-content:space-between;gap:16px;margin-bottom:10px}.order-items{display:grid;gap:8px;margin:14px 0}.order-item{display:flex;align-items:center;gap:10px;color:#49627f}.order-item img{width:52px;height:52px;object-fit:contain;background:#eef5fb}.order-card span,.order-card small{color:#60758f;text-transform:capitalize}.error{color:#b34d5b}</style>
